// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentImageController from "./comment_image_controller"
application.register("comment-image", CommentImageController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserAvatarController from "./user_avatar_controller"
application.register("user-avatar", UserAvatarController)
